# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
        exclude: '^(.devcontainer/|.github/|.pre-commit-config.yaml)'
      - id: end-of-file-fixer
        name: Check for newline at end of file
        exclude: '^(.devcontainer/|.github/|.pre-commit-config.yaml)'
        exclude_types: [svg, json]
      - id: requirements-txt-fixer
        name: Organize requirement files

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    - id: codespell
      name: Check spelling
      exclude: '^(.devcontainer/|.github/|.pre-commit-config.yaml)'
      exclude_types: [svg, json]
      files: docs/

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        name: Check for linting errors on MarkDown files
        exclude: .github/styles
        args:
          - --config=.github/.markdownlint.yaml
          - --fix

  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.11.2
    hooks:
      - id: markdown-link-check
        name: Check for invalid/dead Links
        description: Extracts links from markdown texts and checks they're all alive (i.e. return status 200 OK).
        entry: markdown-link-check
        language: node
        types: [markdown]
        stages: [commit, push, manual]
        args:
          - --quiet
          - --config=config.json

  - repo: https://github.com/errata-ai/vale
    rev: v3.4.1
    hooks:
      - id: vale
        name: Vale - style and grammar checks
        exclude: '^(.devcontainer/|.github/|.pre-commit-config.yaml)'
        files: docs/
