extends: existence
message: "Spell out all ordinal numbers ('%s') in text."
link: 'https://developers.google.com/style/numbers'
level: error
nonword: true
tokens:
  - \d+(?:st|nd|rd|th)\s(?:of\s(?!January|February|March|April|May|June|July|August|September|October|November|December))
